spring:
  application:
    name: library

  datasource:
    url: ${LIBRARY_DB_URL}
    username: ${LIBRARY_DB_USERNAME}
    password: ${LIBRARY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
